default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: stacksocial-dev

test:
  <<: *default
  database: stacksocial-test

production:
  <<: *default
  database: stacksocial-prod
